# Generated by Django 3.0 on 2020-11-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_pizza_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppings',
            name='name',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
